#!/bin/bash 

usage() {
    echo "Usage: $0 [ARGS]"
	echo "Arguments:"
	echo "-g|--gc-bed	      				BED format file produced by BigWigAverageOverBed over a gc5BaseBW file."
	echo "-b|--bed    					BED/bedMethyl format file(s) to compare."
    echo "-o|--outdir    					Directory to output files."
    echo "-k|--keep-cols    					Keep these columns in the output. Provide as comma-separated list. Keeps original BED3 cols by default."
    echo "-h|--help    					Show this help text."
}

OPTSTRING="g:b:o:k:"
##### Arg parsing #####
while getopts ${OPTSTRING} opt; do
  case ${opt} in
	g|gc-bed) GCREF=$OPTARG;;
    b|bed) BED=$OPTARG;;
    k|keep-cols) KEEP_COLS=$OPTARG;;
	o|outdir) OUT_DIR=$OPTARG;;
    h|help|?) 
		usage
		exit 0 
		;;
  esac
done

if [ -z "$GCREF" ] || [ -z "$BED" ] || [ -z "$OUT_DIR" ]; then
  echo "Required values not provided."
  usage
  exit 1
fi

bedtools intersect -a $BED -b $GCREF -wa -wb |\
cut -f 1-3,$KEEP_COLS > $OUT_DIR/$(basename $BED).percentGC.bed
